### ISSUE TITLE
Reproducing reasonable results on CIFAR-10? 

### ISSUE THREAD

**Issue by jkli1998** [YichengDWu/tinyedm#45]
Hi,
Thank you for the great implementation!
I'm really curious to know whether you have successfully achieved promising FID on any unconditional generation dataset.

Thank you!

**Comment by YichengDWu** [comment]
Hi, 

I haven't implemented the code to compute FID, contribution is welcomed : ). However `generate.py` is provided to generate images from a checkpoint, so you should be able to compute the FID with your own script after that.

Note that my implementation is conditioned by default. Set https://github.com/YichengDWu/tinyedm/blob/main/experiments/conf/cifar10.yaml#L31 to `-1` if you want unconditional generation.

**Comment by YichengDWu** [comment]
Also please consider starring this repository!

**Comment by YichengDWu** [comment]
Quick update: After 1700 epochs, I got an FID of 4.0. Continuing the training seems to have encountered the problem of overfitting. Considering that I did not use any data augmentation other than random flip and the CIFAR-10 dataset is small, this may be a reasonable result.
